### DISCUSSION TITLE
initial ideas to followup on

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [Mariusthvdb/custom-attributes#2] [Ideas]
- configuration option, instead of hard coding filtered attributes
- find a way to not filter `options` on a select or input_select entity, but do filter on an enum device_class (which was my whole purpose to begin with)

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

For the first one, a lovelace config can be used. I was sure that Home Assistant front-end should have a way to send the entity to a dialog component. I have checked and each `ha-more-info-dialog` has an `_entityId` property that tells you which is the entity associated to that more-info dialog and the `ha-attributes` has an `__stateObj` property with a lot of information about the entity (and among of them `entity_id`). Knowing this, it is possible to do something like this:

```yaml
custom_attributes:
  filter_attributes:
    ## Filter attributes from specific entities
    sensor.my_sensor:
      - some_attribute
      - some_attribute
    ## Filter attributes from entities that match a glob
    "light.kitchen_*":
      - some_attribute
      - some_attribute
    "sensor.*battery*":
      - some_attribute
      - some_attribute
    ## Filter attributes from domains
    "person.*":
      - some_attribute
      - some_attribute
```

For the second, I need some explanation to understand it.

**Reply by Mariusthvdb** [reply]
that is wonderful, and indeed provides us with very detailed options to customize. 
where do we place the file/config to have the frontend read that globally? 

as for the second:

consider these 2 type of entities:

entities with a `device_class: enum` and entities of domain `select` and` input_select`.
Somehow the dev team thought it fit to not filter the `device_class: enum` in the filtered_attributes. So when opening a more info on those, we see a list of possible values. 

Problem: attribute for both are called `'options`'

My quest here started, because I feel that is not something we need to show in the dashboard, so I want to filter those `options` for the `device_class: enum`, but not filter them for the `(input_)select`.

I tested the first prototype we now have, and it does filter on entities of both types.

given the fine-grained options we have to set those custom_attributes: maybe we can set them only on a certain device_class too? its not something I ever did in regular customize, but maybe this is different?

**Reply by elchininet** [reply]
>where do we place the file/config to have the frontend read that globally?

The same as `kiosk-mode`, in the lovelace dashboard config, we can read it.

>given the fine-grained options we have to set those custom_attributes: maybe we can set them only on a certain device_class too? its not something I ever did in regular customize, but maybe this is different?

It is possible to check the device_class of an entity (I saw it in one of the properties of the `ha_attributes`), so yes, that is possible. But having a fine grain options that you can apply to specific entities_ids or entities_ids that match a certain glob, do you think that it is necessary to make distinction for device_class? For example, the entities of my printer are device_class enum, but I can include them if I use something like `sensor.hp_envy*`.

**Reply by elchininet** [reply]
If you agree with this config I can implement it when I have a chance:

```yaml
custom_attributes:
  filter_attributes:
    ## Filter attributes from specific entities
    sensor.my_sensor:
      - some_attribute
      - some_attribute
    ## Filter attributes from entities that match a glob
    "light.kitchen_*":
      - some_attribute
      - some_attribute
    "sensor.*battery*":
      - some_attribute
      - some_attribute
    ## Filter attributes from domains
    "person.*":
      - some_attribute
      - some_attribute
```

**Reply by Mariusthvdb** [reply]
> The same as kiosk-mode, in the lovelace dashboard config, we can read it.

already set it up, so I am ready for testing ;-)
per dashboard settings in yaml:
```
button_card_templates: !include_dir_merge_named ../button_card_templates
decluttering_templates: !include_dir_named ../decluttering_templates
kiosk_mode: !include ../kiosk-mode/kiosk-mode.yaml
custom_attributes: !include ../custom_attributes/custom_attributes.yaml

views:
```
> But having a fine grain options that you can apply to specific entities_ids or entities_ids that match a certain glob, do you think that it is necessary to make distinction for device_class? For example, the entities of my printer are device_class enum, but I can include them if I use something like sensor.hp_envy*.

yes, for a few entities that would be fine. But, the `device_class: enum` is rather large:

<img width="688" alt="Scherm­afbeelding 2023-12-12 om 15 52 30" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/3df33e57-5009-4be3-91b7-1a954020c9a2">

it would be way easier and probably more logically understandable if we could simply target that device_class and filter the enum attributes in that device_class, and on that device_class alone

**Reply by elchininet** [reply]
Maybe, I am not getting it. This is my printer, its device_class is `enum` (the enum options are "Possible states"). What do you expect to hide here and what could be the proposed code to do it:

![image](https://github.com/Mariusthvdb/custom-attributes/assets/3728220/e913359f-5a1e-420c-aea3-223643ea1069)

**Reply by elchininet** [reply]
The number of `enum` device_class that I have in my system is `8`. 😅

**Reply by Mariusthvdb** [reply]
I would expect to hide the 'options', which apparently in English shows as 'Possible states'

I dont understand why you would still see that if you have the 'options' filter now hardcoded in the custom-attributes 

if I were you, id also add the command_set to the filters on the HP entities;-)

**Reply by Mariusthvdb** [reply]
just image how we can cleanup the interface of this:
<img width="540" alt="Scherm­afbeelding 2023-12-12 om 16 32 46" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/5e38da49-2251-4295-83d7-30d8ee635493">

...

**Reply by elchininet** [reply]
>I would expect to hide the 'options', which apparently in English shows as 'Possible states'

I get it now, you want to hide the options in all entities that have `device_class` enum.

>I dont understand why you would still see that if you have the 'options' filter now hardcoded in the custom-attributes

Because I disabled the plugin to be able to debug without any interference.

>if I were you, id also add the command_set to the filters on the HP entities;-)

Meh, I don‘t care 😅

**Reply by elchininet** [reply]
Taking into account what you want to achieve, I am thinking in something like this:

```yaml
custom_attributes:
  filter_attributes:
    by_entity_id:
      ## Filter attributes from specific entities
      sensor.my_sensor:
        - some_attribute
        - some_attribute
      ## Filter attributes from entities that match a glob
      "light.kitchen_*":
        - some_attribute
        - some_attribute
      "sensor.*battery*":
        - some_attribute
        - some_attribute
      ## Filter attributes from domains
      "person.*":
        - some_attribute
        - some_attribute
    by_device_class:
      enum:
        - some_attribute
        - some_attribute
      battery:
        - some_attribute
        - some_attribute
      motion:
        - some_attribute
        - some_attribute
```

The only thing that complicates things a bit is that these filters should be merged if one entity match with multiple filters, I have an idea for that, I need to check if it is doable.

**Reply by Mariusthvdb** [reply]
would you also be able to add

yes, that seems magic, great way of indication the level at which to set the filters. cool.

would you also be able to add a level `by_domain` and `by_glob`? I am aware you can use the glob for that domain (as you show in your example) but a `per_domain` would be even shorter and more clear to see. As would the `by_glob`

that way we would almost perfectly follow what we can do with regular customize. (this is still valid for core, so great to follow the same 'logic':
```
# per entity
customize: 

# per glob
customize_glob:

#per domain
customize_domain

#on any entity
customize:
  '*.*':

```
Makes me wonder: this can only be done in that separate file? I just figured, maybe we can set it on a card level too per entity, something like

```
type: entities
entities:
  - entity: sensor.my_sensor
     custom_attributes:
        - entity_picture
 - entity: device_tracker.my_printer
    custom_attributes:
      - source
 ```

**Reply by Mariusthvdb** [reply]
btw, as for the merging: in customize, the individual entity mod always overrides any possibly conflicting glob. Maybe thats a thought for this too? 

since were for now only talking of adding an extra filter, I suppose there is no real harm done yet. It might be a bit more complex if we are in fact able to 'unfilter' attributes, and an individual entity would need to unfilter the same attribute that was 
filtered in a glob.

the individual setting would than be overriding that, and fix the conflict?
does that make sense?

**Reply by elchininet** [reply]
>would you also be able to add a level by_domain and by_glob? I am aware you can use the glob for that domain (as you show in your example) but a per_domain would be even shorter and more clear to see. As would the by_glob

Yes, that is possible. But if there is a `by_glob` I would remove the globs from `by_entity_id` and from `by_domain`.

```yaml
custom_attributes:
  filter_attributes:
    by_entity_id:
      ## Filter attributes from specific entities
      sensor.my_sensor:
        - some_attribute
        - some_attribute
    by_glob:
      ## Filter attributes from entities that match a glob
      "light.kitchen_*":
        - some_attribute
        - some_attribute
      "sensor.*battery*":
        - some_attribute
        - some_attribute
    by_domain:
      ## Filter attributes from specific domains
      person:
        - some_attribute
        - some_attribute
    by_device_class:
      ## Filter attributes from specific device classes
      enum:
        - some_attribute
        - some_attribute
      battery:
        - some_attribute
        - some_attribute
      motion:
        - some_attribute
        - some_attribute
```

>Makes me wonder: this can only be done in that separate file? I just figured, maybe we can set it on a card level too per entity, something like

No, that would not be possible. What you add to cards is used to render the cards inside the specific card component. That is not related with the more-info dialogs. More-info dialogs don‘t have context about what you inserted in a card even if an entity in that card was the one that triggered an event to open the more-info dialog.
