### DISCUSSION TITLE
except  (show_only) filter

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [Mariusthvdb/custom-attributes#36] [Ideas]
was just reading the commit changes for the all filter, and then it dawned on me we might also benefit from an except filter.

it would do the same as all, except leave an attribute, or a couple out of the all filter

something like:

```
by_glob:

  device_tracker.google_*:
    - show_only:
        - mac
        - ip
 ```
it would require the nested object, but I hope that would not be a problem? examples on glob here, but it would go for all other by_ filters

**Comment by elchininet** [comment]
That could be solved with the `unfilter_attributes` property that you had in mind (I have it almost ready but I paused it because of the issues that appeared yesterday), It should be something like this:

```yaml
custom_attributes:
  filter_attributes:
    by_glob:
      device_tracker.google_*:
        - all
  unfilter_attributes:
    by_glob:
      device_tracker.google_*:
        - mac
        - ip
```
