### DISCUSSION TITLE
Unfilter

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [Mariusthvdb/custom-attributes#4] [Ideas]
it might be a nice option if we could also **unfilter** any of the filtered_attributes that are filtered by default by the core Frontend in
https://github.com/home-assistant/frontend/blob/dev/src/data/entity_attributes.ts

let's say Id want to show the attribute `device_class` which is currently filtered, it would be magic if we could set something like:
```
custom_attributes:
  unfilter_attributes:

## Unfilter attributes from specific entities
    sensor.my_sensor:
      - unit_of_measurement
    
## Unfilter attributes from entities that match a glob
    "*.*":
      - device_class

## Unfilter attributes from domains
    "light.*":
      - color_temp
      - brightness
    "person.*":
      - friendly_name
```
