### ISSUE TITLE
glob filter not applied to binary

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-attributes#18]
Well, there is a first for everything, our first Issue!

I found this:

using:
```
filter_attributes:

  by_glob:

    '*.*':
      - icon_color
    device_tracker.google*:
      - all #is_guest

  by_domain:

    binary_sensor:
      - hysteresis

    light:
      - all

    siren:
      - available_tones

  by_device_class:

    enum:
      - options

  by_entity_id:

    sensor.cpu_speed:
      - brand
```

the `icon_color` attribute on the `binary_sensor` entities is not filtered. all others are but these remain in view

I suppose somehow the order of filters, or hierarchy is troubling me here?

**Comment by elchininet** [comment]
This is per the spec, remember that `by_domain` overrides `by_glob`, so if it matches an entity `by_domain` and there was also a matcher with `by_glob` it takes the former.

**Comment by elchininet** [comment]
It is already on the README:

>**filter_attributes > by_glob**: This parameter can be overriden by any other parameter in `filter_attributes`.

**Comment by elchininet** [comment]
I think that at the end you are searching for merging the filters isntead of overriding them.

**Comment by Mariusthvdb** [comment]
right, I didn't realize a domain filter on `hysteresis ` would override the glob filter on` icon_color`

I only thought of identical filters....

my solution for now would probably be to explicit the threshold sensors and add the hysteresis to those, let me see if that is an easy task.

**Comment by Mariusthvdb** [comment]
I suppose ultimately merging those would be best yes, even though in the above scenario, it seems a bit silly to apply the filter to all binaries, while there are only a few (14) that have that.

Doesn't matter, in any scenario, the merge would make life easier on the user dont you think?

**Comment by elchininet** [comment]
This should work with the current approach:

```yaml
filter_attributes:

  by_glob:

    '*.*':
      - icon_color
    device_tracker.google*:
      - all #is_guest

  by_domain:

    binary_sensor:
      - hysteresis
      - icon_color

    light:
      - all

    siren:
      - available_tones

  by_device_class:

    enum:
      - options

  by_entity_id:

    sensor.cpu_speed:
      - brand
```

As you know that domain overrides the glob you just need to repat the filter there, it will do it only in that domain, in the rest it will match the glob.
