### ISSUE TITLE
Group not filtered

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-attributes#37]
**Describe the bug**

**To Reproduce**

group entities seem not to be filtered, see below error in screenshot

```
  by_entity_id:

    sensor.cpu_speed:
      - brand

    group.media_players_device_trackers:
      - all

    group.hub_device_trackers:
      - all
```
**Expected behavior**

fall attributes fine, no dropdown attributes box
**Screenshots**

<img width="698" alt="Scherm­afbeelding 2023-12-15 om 15 59 56" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/469866bf-2936-4fcc-ad57-4537cef2c5ed">

<img width="588" alt="Scherm­afbeelding 2023-12-15 om 15 56 25" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/c6222f87-0fac-43b7-bca7-08554e8c79d3">

<img width="558" alt="Scherm­afbeelding 2023-12-15 om 15 56 32" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/b1510e1e-efc2-465e-aaa3-16111852d09c">

**Desktop (please complete the following information):**
 - OS: 2023.12.3
 - Browser Mac Safari
 - Version Versie 17.1.2 (19616.2.9.11.12)

**Additional context**

legacy group yaml:
```
group:
  hub_device_trackers:
    name: Hub device trackers
    all: true
    entities: &trackers
      - device_tracker.ha_main
      - device_tracker.synology_diskstation
      - device_tracker.iungo
      - device_tracker.solaredge
      - device_tracker.ikea_tradfri
      - device_tracker.philips_hue_1
      - device_tracker.philips_hue_2
      - device_tracker.philips_hue_3
      - device_tracker.plugwise_smile
      - device_tracker.somfy_tahoma
```

Dom Path to attributes Dropdown:

<img width="820" alt="Scherm­afbeelding 2023-12-15 om 15 58 44" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/f8ec5011-a708-4b2b-86ab-bb70a71b075e">

Note that a group without a dropdown box also shows the same error:

<img width="573" alt="Scherm­afbeelding 2023-12-15 om 16 11 57" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/2db40713-8b6a-4654-b853-f259baf28a58">

<img width="696" alt="Scherm­afbeelding 2023-12-15 om 16 12 05" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/3ffede0e-715b-461d-aba8-0f3f42bc0e27">

these group members dont have any attributes to show, so the box is not rendered. the error is ugly though
