### ISSUE TITLE
unflter on device_class adds 'device_class :' to dev tools state on single entity_id

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-attributes#47]
**Describe the bug**

if adding the unfilter to device_class on sensor/binary_sensors, there is 1 entity showing both the regular `device_class:` in developer-tools/state, And the custom `device_class :`

as far as I can see, it is only showing on this particular entity, which I can not explain why
**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1014" alt="Scherm­afbeelding 2023-12-18 om 10 36 57" src="https://github.com/Mariusthvdb/custom-attributes/assets/33354141/040c5849-e4cc-456c-8b8a-f741f4d7376b">

**Dom Path of attributes dropdown box**
Always include screenshot to the path of the attributes that error
We cant help you without that exact info

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**The yaml config if applicable**
```yaml
unfilter_attributes:

#special boolean setting for all
# unfilter_all: true #/ false

  by_domain:
# filtered by Home Assistant by default
    binary_sensor:
      - device_class

    sensor:
      - device_class
```

**Additional context**

debug in inspector:
```
{
    "hide": [
        "icon_color",
        "id"
    ],
    "unhide": [
        "device_class"
    ]
}
```
